name       : gst-transcoder
version    : 1.14.1
release    : 4
source     :
    - https://github.com/pitivi/gst-transcoder/archive/1.14.1.tar.gz : ca2c5124a267b16483afdf87e97f48b564dde21b26706fa8097cae58fc46dddb
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : GStreamer Transcoding API
description: |
    GStreamer Transcoding API
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
