name       : gst-transcoder
version    : 1.14.0
release    : 3
source     :
    - https://github.com/pitivi/gst-transcoder/archive/1.14.0.tar.gz : 9861dd51d726fc59511f86e85249e31511ebf0d1744a1100881fc1df63af3839
license    : LGPL-2.1
component  : multimedia.library
summary    : GStreamer Transcoding API
description: |
    GStreamer Transcoding API
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
setup      : |
    export LC_ALL=en_US.utf8
    %meson_configure
build      : |
    export LC_ALL=en_US.utf8
    %meson_build
install    : |
    export LC_ALL=en_US.utf8
    %meson_install
