name       : gst-transcoder
version    : 1.8.2
release    : 1
source     :
    - https://github.com/pitivi/gst-transcoder/archive/1.8.2.tar.gz : 4a0b9be50b7ac06358d148220944e1b2acd5dedc8ad3cd8c8188645b62f3c616
license    : LGPL-2.1
component  : multimedia.library
summary    : GStreamer Transcoding API
description: |
    GStreamer Transcoding API
builddeps  :
    - pkgconfig(gstreamer-pbutils-1.0)
    - meson
setup      : |
    ./configure --prefix=/usr --libdir=lib64
build      : |
    %make
install    : |
    %make_install
