name       : gst-transcoder
version    : 1.12.2
release    : 2
source     :
    - https://github.com/pitivi/gst-transcoder/archive/1.12.2.tar.gz : a9f67fbe5113d2da54b9754ba02747eec8e68f90a386e49c003a88d174aedc32
license    : LGPL-2.1
component  : multimedia.library
summary    : GStreamer Transcoding API
description: |
    GStreamer Transcoding API
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
setup      : |
    export LC_ALL=en_US.utf8
    %meson_configure
build      : |
    export LC_ALL=en_US.utf8
    %meson_build
install    : |
    export LC_ALL=en_US.utf8
    %meson_install
