name       : gst-transcoder
version    : 1.16.0
release    : 5
source     :
    - https://github.com/pitivi/gst-transcoder/archive/1.16.0.tar.gz : b5e65c70f2827aee42810120ca9637fd1f56e7cccf825b1b2f20e575cebdcd62
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : GStreamer Transcoding API
description: |
    GStreamer Transcoding API
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
